NeonGeckoCom/neon_speech

- neon_speech/mic.py
Add method to play confirmation/start_listening sound
Update type annotations for accuracy and to resolve warnings
Cleanup deprecated signal 'startListening'
> Cleanup docstrings and add audio confirmation to get_response calls

- Dockerfile
- README.md
- neon_speech/__main__.py
- requirements/docker.txt
- requirements/requirements.txt
- setup.py
Update Dockerfile and supporting documentation
Use get_messagebus to handle Neon configured messagebus
> Improved Container Support

- neon_speech/__main__.py
- requirements/requirements.txt
Add call to init_config_dir
Update dependencies
Remove redundant call to run bus client
> Add one-time config initialization

- .github/workflows/unit_tests.yml
- neon_speech/__main__.py
- neon_speech/hotword_factory.py
- neon_speech/listener.py
- neon_speech/plugins/modules/background/__init__.py
- requirements/requirements.txt
- requirements/test_requirements.txt
- tests/api_method_tests.py
Implement upstream HotwordFactory directly
Encapsulate default config errors thrown in ovos-core
Encapsulate plugin errors
Improved test exception handling
> Deprecate HotwordFactory and minor Bugfixes

- neon_speech/listener.py
Cleanup dead server-related code
> Remove AudioProducer init for servers (no mic input to handle)

- .github/workflows/license_tests.yml
- tests/license_tests.py
> add license tests and workflow

- .github/workflows/unit_tests.yml
- neon_speech/service.py
- requirements/requirements.txt
- tests/api_method_tests.py
- tests/license_tests.py
Handle audio data in addition to file references in messagebus API methods with added unit tests
> Add encoded audio bytes handling to API Methods

- Dockerfile
- neon_speech/service.py
- requirements/docker.txt
- requirements/requirements.txt
- requirements/test_requirements.txt
- tests/unit_tests.py
Add git to container for installing plugins from git
Added logging around API STT method
> Add git to containers, logging updates

- .github/workflows/unit_tests.yml
- Dockerfile
- README.md
- docker_overlay/etc/OpenVoiceOS/default.yaml
- docker_overlay/etc/OpenVoiceOS/ovos.conf
- docker_overlay/etc/neon/neon.yaml
- docker_overlay/root/.config/neon/neon.conf
- neon_speech/__main__.py
- neon_speech/cli.py
- neon_speech/listener.py
- neon_speech/mic.py
- neon_speech/service.py
- neon_speech/stt.py
- neon_speech/utils.py
- requirements/docker.txt
- requirements/requirements.txt
- requirements/test_requirements.txt
- tests/api_method_tests.py
- tests/unit_tests.py
Depends on https://github.com/NeonGeckoCom/neon-skill-utils/pull/325
**NOTICE** This removes Python 3.6 support
> Deprecate neon_utils.configuration and use mycroft.configuration

- requirements/requirements.txt
Removes extras that include unused WW plugins
> Remove inherited WW plugin dependencies from neon_speech

- .github/workflows/publish_release.yml
- .github/workflows/publish_test_build.yml
- Dockerfile
- docker_overlay/etc/neon/neon.yaml
- neon_speech/cli.py
- neon_speech/utils.py
- requirements/docker.txt
Add docker container with default model included
> Add CLI entrypoint to init an installed plugin

- docker_overlay/etc/OpenVoiceOS/ovos.conf
- docker_overlay/etc/neon/neon.yaml
- requirements/requirements.txt
Update vosk plugin dependency version
Update default WW config
Cleanup ovos docker config
> Default WW Plugin updates and fix

- docker_overlay/etc/xdg/neon/neon.yaml
- neon_speech/mic.py
- neon_speech/service.py
- requirements/requirements.txt
Added default webrtc VAD plugin and config
Refactor WW handling to ovos-core listening modes
> Implement ovos-core listening modes for WW handling

- .github/workflows/publish_release.yml
- .github/workflows/publish_test_build.yml
- neon_speech/__main__.py
- neon_speech/listener.py
- neon_speech/service.py
- neon_speech/utils.py
- tests/api_method_tests.py
- tests/unit_tests.py
Init `voice` log on module start
Update log references to neon_utils
Update pypi action to release v1
> Update log handling

- docker_overlay/etc/neon/neon.yaml
- neon_speech/listener.py
- requirements/docker.txt
Raise exception if STT return is empty
Spec vosk as default fallback STT plugin
Prevent emitting empty STT returns to skills
> Improved STT Fallback Handling

- neon_speech/listener.py
https://github.com/OpenVoiceOS/ovos-core/pull/238
> Add config handling to mic init retry

- .github/workflows/license_tests.yml
- .github/workflows/publish_release.yml
- .github/workflows/publish_test_build.yml
- .github/workflows/pull_master.yml
- .github/workflows/unit_tests.yml
Implements workflows from shared repository
This is the first core repository being tested with these shared workflows, so the workflow branch will need to be updated before a stable release of this package
> Implement shared workflows

- requirements/requirements.txt
Update vosk dependency to remove dependency patching
> Update vosk dependency and remove dependency patch

- neon_speech/listener.py
- neon_speech/service.py
- requirements/test_requirements.txt
- tests/unit_tests.py
Add unit tests for Speech Service
Add some improvements and fixes around hotword reloading
Update service signature to match other modules
> Add messagebus API to interact with configured wake words

- neon_speech/listener.py
- neon_speech/mic.py
- neon_speech/service.py
- requirements/requirements.txt
- tests/unit_tests.py
Write hotword changes to config and allow config watcher to handle reload. Includes fixes to maintain compat. with ovos-core
Relates to https://github.com/OpenVoiceOS/ovos-core/pull/288
> Write hotword changes to config

- Dockerfile
- requirements/docker.txt
- requirements/requirements.txt
- requirements/test_requirements.txt
- tests/unit_tests.py
Update core requirements to stable versions
Update Nemo STT plugin (docker) to first stable release
There is a bug with nemo STT dependency resolution. This is pinning an alpha version to work around the issue
> Stable Dependencies

- neon_speech/service.py
- requirements/requirements.txt
- tests/unit_tests.py
Handle config write exceptions around WW changes
Closes #135
> Add exception handling around WW changes

- neon_speech/service.py
Prevent trying to set a results_event for non-streaming STT when internet is connected
> Add check for results_event before trying to set it

- .github/workflows/publish_release.yml
Update automation to publish prereleases
> Update automation to prep release

- .github/workflows/publish_release.yml
- .github/workflows/publish_test_build.yml
Fix release automation
Fix refactor from #144
> Fix alpha release automation change

- .github/workflows/license_tests.yml
- .github/workflows/publish_release.yml
- .github/workflows/publish_test_build.yml
- .github/workflows/unit_tests.yml
Troubleshooting Docker failures with GH Automations
Troubleshooting failures seen in #148 
https://github.com/NeonGeckoCom/neon_speech/actions/runs/4867541264
> Troubleshoot Docker build failures

- neon_speech/listener.py
- neon_speech/service.py
- neon_speech/stt.py
- requirements/requirements.txt
Resolve race condition at startup
Fix upstream config handling for non-streaming plugins
Closes #150
> Fix non-streaming plugin config compat. with ovos-plugin-manager

- requirements/test_requirements.txt
- tests/unit_tests.py
Add test coverage for fix added in #153
#153
> Add test coverage for non-streaming STT init

- .gitignore
- neon_speech/__main__.py
- neon_speech/listener.py
- neon_speech/mic.py
- neon_speech/service.py
- neon_speech/stt.py
- neon_speech/utils.py
- requirements/requirements.txt
- requirements/test_requirements.txt
- tests/api_method_tests.py
- tests/unit_tests.py
Refactor to remove `mycroft` and `mycroft-messagebus-client` dependencies
> Refactor on ovos-listener module

- neon_speech/__main__.py
- requirements/requirements.txt
> Add malloc logging to speech service

- neon_speech/__main__.py
- neon_speech/service.py
- tests/api_method_tests.py
Refactor PID lock and ready_settings to `voice` to prep move to Dinkum listener
https://github.com/NeonGeckoCom/neon-image-recipe/pull/102
> Refactor 'speech' to 'voice' for future compat.

- neon_speech/__main__.py
- neon_speech/cli.py
- requirements/requirements.txt
Refactor init to minimize work done at module init
Update Dinkum Listener dependency
> Refactor config init to CLI and out of `main` method

- neon_speech/service.py
- requirements/requirements.txt
- tests/unit_tests.py
Update Dinkum listener dependency and remove config handling patches
https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/41
> Update Dinkum listener dependency and clean up config reload handling

- requirements/requirements.txt
- tests/unit_tests.py
Re-implement tests for hotword reloading
https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/40
> Replace Hotword reload tests

- neon_speech/cli.py
- tests/unit_tests.py
> Implement tests for CLI module

- neon_speech/__main__.py
- requirements/requirements.txt
- setup.py
Mark old CLI entrypoint as deprecated
Update dependencies to stable versions
> Update dependencies and mark deprecation

- Dockerfile
- requirements/requirements.txt
Set default XDG_CONFIG_HOME envvar in Dockerfile
Update ovos-dinkum-listener dependency
> Update container config handling and resolve logged warnings

- requirements/requirements.txt
Update dependencies for compat. with https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/67
Needs https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/67
> Update Dinkum Listener dependency

- requirements/requirements.txt
Test with stable dependencies in Dinkum listener
https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/69
> Stable dependencies for release

- neon_speech/service.py
- neon_speech/transformers.py
- requirements/requirements.txt
Override AudioTransformersService to add timing context and metrics reporting
Override listener handlers to add timing context and metrics reporting
Adds save_audio timing context and reporting
Adds save_ww reporting
> Add timing metrics

- neon_speech/service.py
Handle local user language changes as global changes for STT handling
> Update global config on local user STT language change

- requirements/requirements.txt
> Update neon-utils dependency to stable release

- requirements/requirements.txt
Update ovos-dinkum-listener dependency to latest alpha including triggered WW fix
> Update dependencies to pin latest ovos-dinkum-listener

- requirements/requirements.txt
Loosen ovos-utils dependency spec
Add back missing ovos-config dependency
> Update dependencies to prep stable release

- requirements/requirements.txt
Update ovos-dinkum-listener dependency to allow latest stable version
Missed in #201
> Update ovos-dinkum-listener depdendency

- .github/workflows/unit_tests.yml
- LICENSE.md
- docker_overlay/root/run.sh
- neon_speech/__init__.py
- neon_speech/__main__.py
- neon_speech/cli.py
- neon_speech/service.py
- neon_speech/stt.py
- neon_speech/transformers.py
- neon_speech/utils.py
- requirements/requirements.txt
- setup.py
- tests/api_method_tests.py
- tests/unit_tests.py
- version.py
Update cli module to set default envvars
Remove references to deprecated `init_config_dir` function
Update Python versions used in testing
Update license notices to 2025
> Update CLI configuration handling and unit tests

- Dockerfile
- neon_speech/__main__.py
Deprecate PIDLock initialization
Resolve Dockerfile warnings
Closes #161
> Deprecate `PIDLock` usage and update Dockerfile to resolve warnings

- .github/workflows/license_tests.yml
- requirements/docker.txt
- requirements/requirements.txt
- requirements/test_requirements.txt
Update alpha dependencies to available stable versions
> Update dependencies to stable versions
