- docker_overlay/etc/neon/neon.yaml
- neon_speech/listener.py
- neon_speech/service.py
- requirements/requirements.txt
Bump minimum neon-utils version
Fix typo in default config `module_spec`
Prevent AudioProducer init without a microphone
> Resolve container config backwards-compatibility

- Dockerfile
Install CPU-only torch to reduce image size per @NeonBohdan suggestion.
Equivalent to https://github.com/NeonGeckoCom/neon_audio/pull/114
Should improve image download delays as reported by @NeonDmitry
> Install CPU-only pytorch from official source to reduce image size

- .github/workflows/unit_tests.yml
- neon_speech/listener.py
- neon_speech/service.py
- requirements/requirements.txt
- tests/unit_tests.py
Add handling for listener configured WW which defaults to `active`
> Identify default WW as active on the bus API

- neon_speech/listener.py
- neon_speech/service.py
Add an option to disable api_stt for low-resource devices (like Mark2)
Move fallback_stt init to first fallback call to reduce work done/memory used at init
> Refactor STT init to reduce memory footprint

- requirements/test_requirements.txt
- tests/api_method_tests.py
- tests/unit_tests.py
Update unit tests to drop neon-messagebus test dependency
> Refactor tests to remove messagebus module dependency

- .github/workflows/unit_tests.yml
- neon_speech/mic.py
- tests/unit_tests.py
Handle exceptions when hotword engines are missing with unit tests
#50
This disables a failing Docker build test that needs to be fixed for GH actions
> Handle hotword engine exception handling with unit tests

- .github/workflows/publish_release.yml
- .github/workflows/publish_test_build.yml
Update Docker actions to explicitly use `diana` runners and not any self-hosted runners
> Specify Docker actions to use `diana` action runners

- docker_overlay/etc/neon/neon.yaml
- neon_speech/service.py
Add config option to disable listener and only run API methods for k8s deployment
Handle read-only config file paths and fallback to `/tmp` for k8s compat.
> Kubernetes/No-audio server compat.

- .github/workflows/license_tests.yml
- neon_speech/service.py
- requirements/docker.txt
- requirements/test_requirements.txt
Add `get_stt` timing metric for audio input
https://github.com/NeonGeckoCom/neon-minerva/pull/3
Includes patch for https://github.com/microsoft/onnxruntime/issues/17631
Updates license tests for dependency with undefined MIT license
> Add timing metrics for minerva testing

- neon_speech/service.py
- requirements/requirements.txt
Override source/destination validation for backwards-compat. with deprecation notice
Pin ovos-dinkum-listener dependency for stable release
> OVOS Dinkum Listener Backwards Compat

- neon_speech/service.py
Adds explicit handling of API input audio to set sample_rate, sample_width, and channels to match listener configuration
Refactor to prevent creating an audio stream object not used for non-streaming STT
https://github.com/NeonGeckoCom/neon-iris/issues/28
> Resample API input wav audio to ensure format matches listener config

- neon_speech/service.py
Handles `client_sent` timestamp and calculates how long it took for the message to be handled in this module
https://github.com/NeonGeckoCom/neon_audio/pull/154
> Add timing metrics for audio input to handler in speech service

- neon_speech/service.py
- tests/api_method_tests.py
Allows for `timing` context sent from a connected client
Adds unit tests to validate timing context handling
Continues #181
> Improved timing context handling with unit tests

- neon_speech/service.py
Adds support for k8s deployments and other instances not running a voice loop to query supported STT languages
> Override ovos.language.stt handler for server/API usage

- neon_speech/cli.py
- neon_speech/utils.py
Fix typo in deprecation version (2.0.0 -> 5.0.0)
Resolve PEP warnings
Fixes typo missed in #190
> Fix deprecation logs and formatting changes

- requirements/requirements.txt
Rolls back update to ovos-dinkum-listener dependency included in release 4.4.0
https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/98
https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/107
https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/110
> Revert ovos-dinkum-listener dependency to previous validated version

- neon_speech/service.py
This makes interactions with the listener more directly comparable with API inputs by timing the same parts of the code.
More consistent with [the docs](https://github.com/NeonGeckoCom/neon-docs/pull/30/files)
> Move STT timing to start at recording end

- neon_speech/service.py
Ensures any surrounding quotes are removed from STT strings
Potentially obviated by https://github.com/OpenVoiceOS/ovos-stt-http-server/pull/20
> Remove quotes from API endpoint

- .github/workflows/unit_tests.yml
- requirements/requirements.txt
- tests/unit_tests.py
Update OVOS dependencies to allow 0.1+
Related to https://github.com/NeonGeckoCom/NeonCore/pull/708
> Update dependencies to allow latest OVOS packages

- neon_speech/service.py
- neon_speech/stt.py
- neon_speech/utils.py
- requirements/docker.txt
- requirements/requirements.txt
- requirements/test_requirements.txt
- tests/api_method_tests.py
- tests/unit_tests.py
Update to use OVOSSttFactory directly
Mark neon_speech.stt module as deprecated
Update dependencies to latest stable versions
Includes patch to handle config updates when FileWatcher fails to report changes
Closes #168 
Relates to #158 
Validated k8s alpha deployment
Tested local Docker instance
Tested against Mark2 latest beta
> Refactor to extend changes in OvosDinkumListener

- .github/workflows/unit_tests.yml
- .github/workflows/update_docker_images.yml
Add Python3.12 and setuptools installation to unit test automation
Add GHA to manually update `dev` and `master` tagged images
> Update unit test and add manual Docker update automation
